import { CancionModelo } from "./cancion.modelo"


export const DatosCanciones:CancionModelo[]=[
new CancionModelo("Kiss Of Fire", "Louis Armstrong", 1952, "Satchmo Signs", "Jazz","imagen2.jpeg", "BMG","louis_armstrong.mp3"),
new CancionModelo("Take Five", "The Dave Bruckek Quarter", 1959, "Time Out", "Jazz", "imagen3.jpeg", "JazzDisco","take_five.mp3"),
new CancionModelo("Another One Bites The Dust", "Queen", 1980, "The Game", "Rock","imagen4.jpeg", "BMG Ariola","queen.mp3"),
new CancionModelo("Come Together", "The Beatles", 1969, "Abbey Road", "Rock", "imagen1.jpeg", "Emi","come_together.mp3"),
new CancionModelo("Nuages", "Django Reinhardt", 1953, "The great artistry", "Jazz", "imagen5.jpeg", "Clef" ,"nuages.mp3"),
new CancionModelo("An Easy Job", "Ozzie Nelson", 1930, "The Uncollected", "Jazz", "imagen6.jpeg", "Big Band" ,"What An Easy Job You've Got.mp3"),
new CancionModelo("Big River", "Johnny Cash", 1954, "The Tennessee Three", "Country", "imagen7.jpeg", "Grand Ole Opry," ,"Big River.mp3"),
new CancionModelo("Move it on Over", "Hank Williams", 1953, "Move It On Over", "Folk", "imagen8.jpeg", "MGM Records" ,"Move it on Over.mp3"),
new CancionModelo("A Country Boy Can Survive", "Hank Williams Jr", 2016, "A Country Boy Can Survive ", "Country", "imagen9.jpeg", "Curb Records" ,"A Country Boy.mp3"),
new CancionModelo("Slow Poke", "Pee Wee King", 1951, "Western Swing Get Together", "Swing", "imagen10.jpeg", "Jasmine" ,"Slow Poke.mp3"),
new CancionModelo("In The Mood", "Glenn Miller", 1944, "Moonlight Serenade", "Jazz", "imagen11.jpeg", "TopLine Records" ,"In The Mood.mp3"),
new CancionModelo("A Castle By The Sea", "Powfu", 2021, "Tell Me Your Feelings", "Indie", "imagen12.jpeg", "Columbia Records" ,"A Castle By The Sea.mp3"),
new CancionModelo("From Your Knees", "John Conlee", 2003, "Classics", "Country", "imagen13.jpeg", "Fellow Travelers" ,"From Your Knees.mp3"),
new CancionModelo("One Day At A Time", "Bradley Walker", 2003, "Blessed", "Country", "imagen14.jpeg", "Guitar Gospel" ,"One Day At A Time.mp3"),
new CancionModelo("Oh! Susanna", "Hillary Klug", 2020, "Howdy Y'all", "Country", "imagen15.jpeg", "DistroKid" ,"Oh! Susanna.mp3"),
new CancionModelo("Dixie's Land", "2nd South Carolina String Band", 1997, "Southern Soldier", "Country", "imagen16.jpeg", "CDBaby" ,"Dixie's Land.mp3"),
new CancionModelo("What You Give", "Tesla", 2009, "Psychotic Suppe", "Rock", "imagen17.jpeg", "Aviator Management GmbH" ,"What You Give.mp3"),
new CancionModelo("Spirit in the Sky", "Norman Greenbaum", 1969, "Spirit in the Sky", "Rock-Blues", "imagen18.jpeg", "Reprise" ,"Spirit in the Sky.mp3"),
new CancionModelo("Devil Always", "Chris Stapleton", 1944, "Starting Over", "Country", "imagen19.jpeg", "Mercury Nashville" ,"Devil Always Made Me Think Twice.mp3"),
new CancionModelo("God Bless The Child", "Shania Twain", 1995, "The Woman In Me", "Country", "imagen20.jpeg", "Polygram Mercury" ,"God Bless The Child.mp3"),
new CancionModelo("Movies", "Jeremy Ivey", 2003, "Waiting Out The Storm", "Americana", "imagen21.jpeg", "Sound Emporium" ,"Movies.mp3"),
new CancionModelo("Rip It Up", "Elvis Presley", 1956, "Elvis", "Rockabilly", "imagen22.jpeg", "RCA Victor" ,"Rip It Up.mp3"),
new CancionModelo("Sing One", "George Strait", 1956, "Honky Tonk Time Machine", "Country", "imagen23.jpeg", "MCA Nashville" ,"Sing One With Willie.mp3"),
new CancionModelo("Time of the Preacher", "Willie Nelson", 1975, "Red Headed Stranger", "Country", "imagen24.jpeg", "Sony Music Entertainment" ,"Time of the Preacher.mp3"),
new CancionModelo("Out of Hand", "Gary Stewart", 1975, "Out Of Hand", "Country", "imagen25.jpeg", "Sony Music Entertainment" ,"Out of Hand.mp3"),
new CancionModelo("Stand By Your Man", "Tammy Wynette", 1968, "Stand By Your Man", "Country", "imagen26.jpeg", "SONY BMG" ,"Stand By Your Man.mp3"),
new CancionModelo("What A Friend We Have In Jesus", "Alan Jackson", 2006, "Precious Memories", "Gospel", "imagen27.jpeg", "EMI Records" ,"What A Friend We Have In Jesus.mp3"),
new CancionModelo("Sympathy For The Devil", "The Rolling Stones", 1970, "Get Yer Ya-Ya's Out!", "Blues Rock", "imagen28.jpeg", "Decca Records" ,"Sympathy For The Devil.mp3"),
new CancionModelo("To Beat the Devil", "Kris Kristofferson", 1970, "Kristofferson", "Country", "imagen29.jpeg", "SONY BMG" ,"To Beat the Devil.mp3"),
new CancionModelo("Солдат", "5'nizza", 2003, "Piatnica", "Country", "imagen30.jpeg", "MOON Records" ,"Солдат.mp3"),
new CancionModelo("Ya Watani", "Marcel Khalife", 1984, "Arabism", "Singer", "imagen31.jpeg", "MOON Records" ,"Ya Watani.mp3"),
new CancionModelo("抜刀隊", "Tayama Masakaju", 1885, "Battō-tai", "Military March", "imagen32.jpeg", "Japanese RECORDS" ,"抜刀隊.mp3"),
new CancionModelo("I'm A Good Old Rebel", "Ry Cooder", 1980, "The Long Riders (Soundtrack)", "Country", "imagen33.jpeg", "OMP RECORDS" ,"I'm A Good Old Rebel.mp3"),
new CancionModelo("Kjempene på Dovrefjell", "Folque", 1975, "På Dovrefjell", "Nordic", "imagen34.jpeg", "Phonogram A/S" ,"Kjempene på Dovrefjell.mp3"),
new CancionModelo("If I Were A Rich Man", "John Williams", 2000, "Fiddler on the Roof", "Singer", "imagen35.jpeg", "Universal Music Group" ,"If I Were A Rich Man.mp3"),
new CancionModelo("Who Only Europe Know", "Rome", 2000, "Le Ceneri Di Heliodoro", "Neofolk", "imagen36.jpeg", "Tristol Music Group" ,"Who Only Europe Know.mp3"),
new CancionModelo("Apkārt Kalnu Gāju", "Vilkači", 2008, "Ko Kundziņi", "Neofolk", "imagen37.jpeg", "Lauska Records" ,"Apkārt Kalnu Gāju.mp3"),
]
